CREATE TABLE Appointments(
AppointmentID INT AUTO_INCREMENT PRIMARY KEY,
PatientID INT NOT NULL,
DoctorID INT NOT NULL,
AppointmentDate DATE NOT NULL,
AppointmentTime TIME NOT NULL,
Status VARCHAR(20) NOT NULL,
FOREIGN KEY(PatientID) REFERENCES Patients(PatientID),
FOREIGN KEY(DoctorID) REFERENCES Doctors(DoctorID));


